name: Lint

on:
  pull_request:
    paths:
      - "Formula/**"
      - ".github/**"
  push:
    branches:
      - main

jobs:
  brew-audit:
    name: brew audit
    runs-on: macos-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Audit formulas
        run: |
          brew audit --formula Formula/solo.rb
          brew audit --formula Formula/hiero-cli.rb

  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: ".github/scripts"
          severity: warning

  rubocop:
    name: rubocop
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"

      - name: Install RuboCop
        run: gem install rubocop

      - name: Run RuboCop
        run: rubocop --config .rubocop.yml Formula/solo.rb Formula/hiero-cli.rb Formula/solo.template.rb

  test-update-script:
    name: update script unit test
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Run update script tests
        run: bash .github/scripts/test-update-solo-formula.sh
